version: '3.1'

services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"   # Client
      - "2888:2888"   # Follower
      - "3888:3888"   # Election
    networks:
      - issuance-batch-processor
    container_name: zookeper

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"   # Native transport
      - "7199:7199"   # JMX
      - "9160:9160"   # Thrift clients
      - "7000:7000"   # Inter-node cluster
      - "7001:7001"   # TLS Inter-node communication (used if TLS enabled)
    networks:
      - issuance-batch-processor
    container_name: cassandra

  sqs:
    image: s12v/elasticmq:latest
    ports:
      - "9324:9324"   # Data
    volumes:
      - ~/.issuance-batch/sqs/elasticmq.conf:/etc/elasticmq/elasticmq.conf
    networks:
      - issuance-batch-processor
    container_name: sqs

  s3:
    image: loyaltyone/s3mock:0.1-SNAPSHOT
    ports:
      - "9090:9090" # http port
    environment:
      - "INITIAL_BUCKETS=l1-dev-issuance-batch"
      - "VERSIONED_BUCKETS=l1-dev-issuance-batch"
    networks:
      - issuance-batch-processor
    container_name: s3

  sns:
    image: s12v/sns:latest
    ports:
      - "9911:9911"
    volumes:
      - ~/.issuance-batch/sns:/etc/sns
    networks:
      - issuance-batch-processor
    depends_on:
      - sqs
    container_name: sns

  proxy-services:
    image: "824691084780.dkr.ecr.us-east-1.amazonaws.com/proxy-services:0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    environment:
      - "PROVIDER_DATA_PATH=/opt/docker/provider-data.json"
    volumes:
      - ~/.proxy-services/provider/data.json:/opt/docker/provider-data.json
    networks:
      - issuance-batch-processor
    container_name: proxy-services

networks:
  issuance-batch-processor:
